---
kind: Service
apiVersion: v1
metadata:
  name: Demo-test-service 
spec:
  selector:
    app: Demo-test
  ports:
    - # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Demo-test-deployment 
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: Demo-test
    spec:
      containers:
        - name: Demo-test-container 
          image: tutum/hello-world
          ports:
            - containerPort: 4000